spring.cloud.stream.bindings.singleOutput.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.input:
  destination: test-input
spring.cloud.stream.bindings.output:
  destination: test-output
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost #192.168.99.100
spring.applicaiton.name: route-to-stream


